# Generated by Django 4.2.11 on 2024-03-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
